/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ATable: typeof import('@arco-design/web-vue')['Table']
    CountryDistribution: typeof import('./src/components/CountryDistribution/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserActivity: typeof import('./src/components/UserActivity/index.vue')['default']
  }
}
